Move networking oneview configurations to DEFAULT section
HewlettPackard/networking-oneview pull request #10
Opened 2018-02-07 18:08 UTC by hugonicodemos

2018-02-07 19:03 UTC, ricardoas requested changes

2018-02-07 19:03 UTC, ricardoas commented on networking_oneview/conf/opts.py
> +# Copyright 2018 Hewlett Packard Enterprise Development LP.
(2016-2018)?

2018-02-07 19:09 UTC, hugonicodemos commented on networking_oneview/conf/opts.py
> +# Copyright 2018 Hewlett Packard Enterprise Development LP.
Done.

2018-02-08 14:54 UTC, ricardoas approved these changes

2018-02-08 14:54 UTC, merged