feature/5301 - Optimize OneView network synchronization operations
HewlettPackard/networking-oneview pull request #15
Opened 2018-02-21 16:51 UTC by GustavoDinizMonteiro

2018-02-21 18:11 UTC, ricardoas requested changes
I think that by implementing this we will bring back the case when database is outdated but both networks exist! I'll think a bit more about it... any help is appreciated!

2018-02-23 17:27 UTC, ricardoas requested changes
I got it... suppose you have a working uplinset mapping and VLAN networks already created at both neutron and oneview (included on uplinsets and all) and somebody delete you "Neutron[uuid]" network from oneview, this is what happens according to your code:
* sync mechanism for networks is triggered (synchronization.py:L134)
* L140: you find the record on sync table
* L144 you fail recovering the oneview net (deleted, right?)
* L148 you clean the record from sync db
and it's over...
I think we should call a network create operation for this case too... the next sync will of course create the network but depending on the time granularity it could take a while.

I'd revert the code and just add a continue to the loop `if oneview_network`... what do you think?

2018-02-26 13:33 UTC, stenioaraujo approved these changes

2018-02-27 18:01 UTC, SauloAislan approved these changes

2018-02-28 13:00 UTC, ricardoas approved these changes

2018-02-28 13:00 UTC, merged