Move uplinkset type and LIG/LI checks to init (no need to redo them)
HewlettPackard/networking-oneview pull request #5
Opened 2018-02-05 19:06 UTC by stenioaraujo

2018-02-07 14:41 UTC, hugonicodemos commented on networking_oneview/ml2/drivers/oneview/mech_oneview.py
> +        common.check_uplinkset_types_constraint(
move those checks to initialize

2018-02-07 16:31 UTC, hugonicodemos commented on tox.ini
> +  pylint -f parseable -d C0111,C0103,E0401,R0914 networking_oneview --ignore=tests,db
+2

2018-02-07 18:52 UTC, hugonicodemos requested changes

2018-02-07 18:52 UTC, hugonicodemos commented on networking_oneview/ml2/drivers/oneview/mech_oneview.py
> +        common.check_uplinkset_types_constraint(
move those checks to initialize.

2018-02-07 18:56 UTC, ricardoas requested changes

2018-02-07 18:56 UTC, ricardoas commented on networking_oneview/ml2/drivers/oneview/mech_oneview.py
> +        common.check_uplinkset_types_constraint(
agreed

2018-02-08 17:17 UTC, hugonicodemos approved these changes

2018-02-14 19:08 UTC, SauloAislan approved these changes

2018-02-15 13:20 UTC, ricardoas approved these changes

2018-02-15 13:20 UTC, GustavoDinizMonteiro approved these changes

2018-02-23 14:10 UTC, ricardoas approved these changes

2018-02-23 14:13 UTC, merged